In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
train = pd.read_csv('train.csv')
train.head()

time  temperature_2m_max (°C)  temperature_2m_min (°C)  \
0  2018-01-01                     29.9                     26.0   
1  2018-01-02                     30.6                     25.7   
2  2018-01-03                     31.8                     25.9   
3  2018-01-04                     30.8                     26.0   
4  2018-01-05                     30.9                     25.2   

   apparent_temperature_max (°C)  apparent_temperature_min (°C)  \
0                           36.3                           31.6   
1                           37.7                           31.2   
2                           40.3                           31.7   
3                           39.1                           31.6   
4                           37.6                           29.9   

  sunrise (iso8601)  sunset (iso8601)  shortwave_radiation_sum (MJ/m²)  \
0  2018-01-01T05:15  2018-01-01T17:49                            17.59   
1  2018-01-02T05:15  2018-01-02T17:50                            19.87   
2  2018-01-03T05:16  2018-01-03T17:50                            20.44   
3  2018-01-04T05:16  2018-01-04T17:50                            20.44   
4  2018-01-05T05:17  2018-01-05T17:51                            20.10   

   rain_sum (mm)  snowfall_sum (cm)  windspeed_10m_max (km/h)  \
0            7.7                0.0                       6.9   
1            9.4                0.0                       7.1   
2            7.8                0.0                       8.1   
3           29.7                0.0                       7.2   
4           22.5                0.0                       6.9   

   windgusts_10m_max (km/h)  winddirection_10m_dominant (°)  \
0                      20.2                           277.0   
1                      18.0                           168.0   
2                      21.2                           125.0   
3                      21.6                           190.0   
4                      21.2                           241.0   

   et0_fao_evapotranspiration (mm)  elevation city  
0                             3.61          0   su  
1                             4.11          0   su  
2                             4.23          0   su  
3                             4.22          0   su  
4                             4.16          0   su

In [3]:
X = pd.DataFrame(train.iloc[:,:-1])
X.drop('rain_sum (mm)', inplace=True, axis=1)
X

time  temperature_2m_max (°C)  temperature_2m_min (°C)  \
0      2018-01-01                     29.9                     26.0   
1      2018-01-02                     30.6                     25.7   
2      2018-01-03                     31.8                     25.9   
3      2018-01-04                     30.8                     26.0   
4      2018-01-05                     30.9                     25.2   
...           ...                      ...                      ...   
13253  2022-12-24                      NaN                      NaN   
13254  2022-12-25                      NaN                      NaN   
13255  2022-12-26                      NaN                      NaN   
13256  2022-12-27                      NaN                      NaN   
13257  2022-12-28                      NaN                      NaN   

       apparent_temperature_max (°C)  apparent_temperature_min (°C)  \
0                               36.3                           31.6   
1                               37.7                           31.2   
2                               40.3                           31.7   
3                               39.1                           31.6   
4                               37.6                           29.9   
...                              ...                            ...   
13253                            NaN                            NaN   
13254                            NaN                            NaN   
13255                            NaN                            NaN   
13256                            NaN                            NaN   
13257                            NaN                            NaN   

      sunrise (iso8601)  sunset (iso8601)  shortwave_radiation_sum (MJ/m²)  \
0      2018-01-01T05:15  2018-01-01T17:49                            17.59   
1      2018-01-02T05:15  2018-01-02T17:50                            19.87   
2      2018-01-03T05:16  2018-01-03T17:50                            20.44   
3      2018-01-04T05:16  2018-01-04T17:50                            20.44   
4      2018-01-05T05:17  2018-01-05T17:51                            20.10   
...                 ...               ...                              ...   
13253  1970-01-01T07:00  1970-01-01T07:00                              NaN   
13254  1970-01-01T07:00  1970-01-01T07:00                              NaN   
13255  1970-01-01T07:00  1970-01-01T07:00                              NaN   
13256  1970-01-01T07:00  1970-01-01T07:00                              NaN   
13257  1970-01-01T07:00  1970-01-01T07:00                              NaN   

       snowfall_sum (cm)  windspeed_10m_max (km/h)  windgusts_10m_max (km/h)  \
0                    0.0                       6.9                      20.2   
1                    0.0                       7.1                      18.0   
2                    0.0                       8.1                      21.2   
3                    0.0                       7.2                      21.6   
4                    0.0                       6.9                      21.2   
...                  ...                       ...                       ...   
13253                NaN                       NaN                       NaN   
13254                NaN                       NaN                       NaN   
13255                NaN                       NaN                       NaN   
13256                NaN                       NaN                       NaN   
13257                NaN                       NaN                       NaN   

       winddirection_10m_dominant (°)  et0_fao_evapotranspiration (mm)  \
0                               277.0                             3.61   
1                               168.0                             4.11   
2                               125.0                             4.23   
3                               190.0                             4.22   
4                               241.0  

In [4]:
X.drop('time', axis=1, inplace=True)

In [5]:
X.drop(['sunrise (iso8601)', 'sunset (iso8601)'], axis=1, inplace=True)

In [6]:
y = pd.DataFrame(train.iloc[:,8])
y

rain_sum (mm)
0                7.7
1                9.4
2                7.8
3               29.7
4               22.5
...              ...
13253            NaN
13254            NaN
13255            NaN
13256            NaN
13257            NaN

[13258 rows x 1 columns]

In [7]:
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(missing_values=np.nan, strategy='most_frequent')

In [8]:
X = imputer.fit_transform(X)
y = imputer.fit_transform(y)
# y = y.reshape(-1,1)
# y

In [9]:
X

array([[ 29.9 ,  26.  ,  36.3 , ..., 277.  ,   3.61,   0.  ],
       [ 30.6 ,  25.7 ,  37.7 , ..., 168.  ,   4.11,   0.  ],
       [ 31.8 ,  25.9 ,  40.3 , ..., 125.  ,   4.23,   0.  ],
       ...,
       [ 31.7 ,  25.6 ,  37.  , ..., 132.  ,   0.  ,   0.  ],
       [ 31.7 ,  25.6 ,  37.  , ..., 132.  ,   0.  ,   0.  ],
       [ 31.7 ,  25.6 ,  37.  , ..., 132.  ,   0.  ,   0.  ]])

In [10]:
y

array([[7.7],
       [9.4],
       [7.8],
       ...,
       [0. ],
       [0. ],
       [0. ]])

In [11]:
X.shape

(13258, 11)

In [12]:
y.shape

(13258, 1)

In [13]:
y.reshape(y.shape[:])

array([[7.7],
       [9.4],
       [7.8],
       ...,
       [0. ],
       [0. ],
       [0. ]])

In [14]:
y.shape

(13258, 1)

In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=101)

In [16]:
from sklearn.ensemble import RandomForestRegressor
regg = RandomForestRegressor()
# Y = y_train.ravel()
# y_train = np.squeeze(y_train)
regg.fit(X_train, y_train)


C:\Users\Naufalqii\AppData\Local\Temp\ipykernel_26356\1355122738.py:5: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  regg.fit(X_train, y_train)


RandomForestRegressor()

In [17]:
test = pd.read_csv('test.csv')
test.head()

id        time  temperature_2m_max (°C)  temperature_2m_min (°C)  \
0   0  2021-08-02                     32.3                     25.3   
1   1  2021-08-03                     31.7                     25.5   
2   2  2021-08-04                     32.6                     25.7   
3   3  2021-08-05                     32.0                     25.7   
4   4  2021-08-06                     31.9                     26.3   

   apparent_temperature_max (°C)  apparent_temperature_min (°C)  \
0                           38.2                           29.6   
1                           37.4                           30.3   
2                           37.1                           30.8   
3                           36.8                           31.1   
4                           36.0                           31.6   

  sunrise (iso8601)  sunset (iso8601)  shortwave_radiation_sum (MJ/m²)  \
0  2021-08-02T05:39  2021-08-02T17:30                            20.79   
1  2021-08-03T05:39  2021-08-03T17:30                            20.01   
2  2021-08-04T05:39  2021-08-04T17:30                            20.89   
3  2021-08-05T05:39  2021-08-05T17:30                            22.19   
4  2021-08-06T05:38  2021-08-06T17:30                            21.84   

   snowfall_sum (cm)  windspeed_10m_max (km/h)  windgusts_10m_max (km/h)  \
0                0.0                       7.6                      16.9   
1                0.0                      10.2                      21.6   
2                0.0                      17.3                      32.4   
3                0.0                      15.8                      29.2   
4                0.0                      20.2                      36.7   

   winddirection_10m_dominant (°)  et0_fao_evapotranspiration (mm)  elevation  \
0                           134.0                             4.45          0   
1                           131.0                             4.32          0   
2                           116.0                             4.73          0   
3                           115.0                             4.96          0   
4                           106.0                             4.99          0   

  city  
0   su  
1   su  
2   su  
3   su  
4   su

In [18]:
z = test.drop(['time', 'city', 'sunset (iso8601)', 'sunrise (iso8601)', 'id'], axis=1)

In [19]:
y_pred = regg.predict(z)
y_pred

c:\Users\Naufalqii\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:402: UserWarning: X has feature names, but RandomForestRegressor was fitted without feature names
  warnings.warn(


array([0.637, 0.567, 0.676, ..., 0.   , 0.   , 0.   ])

In [24]:
df = pd.DataFrame(y_pred)
df.rename(columns={0:'rainfall'})
df.columns = ['rain_sum (mm)']
df.index.name = 'id'
df.to_csv('submission2.csv', index=True)
# df

In [21]:
from sklearn import metrics
print('MSE : ', metrics.mean_squared_error(z, y_pred))

ValueError: y_true and y_pred have different number of output (11!=1)